= TERNOKO API Document
2022-ternoko
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[introduction]]
== 소개
터놓고 API 문서 입니다.

//[[introduction]]
//== 서비스환경
//해당 API서비스의 서버 도메인 환경은 다음과 같습니다.
//
//
//== Domain
//|===
//| 환경 | URI
//
//| 개발서버
//| `todo`
//
//| 운영서버
//| `todo`
//|===

== 회원 API
=== [코치] 내 정보 조회 API
operation::coach-controller-test/find-coach[snippets='http-request,http-response']

=== [코치] 내 정보 수정 API
operation::coach-controller-test/update-coach[snippets='http-request,http-response']

=== [크루] 내 정보 조회 API
operation::crew-controller-test/find-coach[snippets='http-request,http-response']

=== [크루] 내 정보 수정 API
operation::crew-controller-test/update-coach[snippets='http-request,http-response']

=== [코치/크루] 닉네임 중복 검사 API
operation::member-controller-test/check-unique-nickname[snippets='http-request,http-response']

== 면담 가능 시간 API
=== [코치] 면담 가능 시간 저장 API
operation::coach-controller-test/save-calendar-times[snippets='http-request,http-response']

=== [코치] 면담 가능 시간 조회 API
operation::coach-controller-test/find-calendar-times[snippets='http-request,http-response']


== 면담 예약 API
=== [크루] 코치 목록 조회 API
operation::member-controller-test/find-coaches[snippets='curl-request,http-request,http-response']

=== [크루] 면담 예약 신청 API
operation::reservation-controller-test/create-reservation[snippets='curl-request,http-request,http-response']

=== [코치] 면담 예약 목록 조회 API
operation::coach-controller-test/find-all-reservation-by-coach[snippets='http-request,http-response']

=== [크루] 면담 예약 목록 조회 API
operation::reservation-controller-test/find-all-reservations[snippets='curl-request,http-request,http-response']

=== [크루] 면담 예약 단건 조회 API
operation::reservation-controller-test/find-reservation-by-id[snippets='curl-request,http-request,http-response']

=== [크루] 면담 예약 수정 PAI
operation::reservation-controller-test/update-reservation[snippets='http-request,http-response']

=== [코치] 면담 예약 취소 API
operation::reservation-controller-test/cancel-reservation[snippets='http-request,http-response']

=== [크루] 면담 예약 취소 API
operation::reservation-controller-test/delete-reservation[snippets='curl-request,http-request,http-response']
