spring:
  profiles:
    default: local

slack:
  redirectUrl: 'https://localhost:8080/api/login'
  clientId: '3756998338916.3821665111344'
  clientSecret: '7db0d45bf9ae307a3a93522aa0cc4131'
server:
  ssl:
    key-store: classpath:ternoko-keystore.p12
    key-store-type: PKCS12
    key-store-password: 980807
    key-alias: ternoko-keystore
