spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ternoko?serverTimezone=Asia/Seoul
    username: root
    password: root1234
  h2:
    console:
      enabled: true
logging:
  config: classpath:log4j2-local.xml
