spring:
  profiles:
    default: local

slack:
  redirectUrl: 'https://localhost:8080/api/login'
  clientId: '3756998338916.3821665111344'
  clientSecret: '7db0d45bf9ae307a3a93522aa0cc4131'

server:
  ssl:
    key-store: classpath:ternoko-keystore.p12
    key-store-type: PKCS12
    key-store-password: 980807
    key-alias: ternoko-keystore

security:
  jwt:
    token:
      secret-key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno'
      expire-length: 3600000
