spring:
  mail:
    port: 587
    host: smtp.gmail.com
    username: 'ternoko.official@gmail.com'
    password: 'password'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    activate:
      on-profile: local
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ternoko?serverTimezone=Asia/Seoul
    username: root
    password:

slack:
  clientId: '3756998338916.3821665111344'
  clientSecret: 'secret'
  botToken: 'botToken'
  url: 'https://slack.com'
  sendApi: '/api/chat.postMessage'
  destination: 'develop'

security:
  jwt:
    token:
      secret-key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno'
      expire-length: 3600000

logging:
  config: classpath:log4j2-local.xml

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  health:
    mail:
      enabled: false


